"""Tests for HardwareController validation chain — pump-only architecture.

Validates the complete spray-command validation chain:
  device online → correct mode → e-stop inactive →
  duration valid → not spraying → command not duplicate → send to ESP32
"""

import os
os.environ["ESP32_CONNECTION"] = "mock"

from app.services.hardware_controller import HardwareController
from app.services.serial_manager import serial_manager

serial_manager._mock_mode = True
serial_manager.connect()

def _fresh_controller() -> HardwareController:
    ctrl = HardwareController()
    ctrl._current_mode = "manual"
    return ctrl


class TestManualSprayValidation:
    """POST /api/v1/spray/manual — pump-only contract."""

    def test_valid_pump_only_request_succeeds(self):
        ctrl = _fresh_controller()
        result = ctrl.manual_spray("device-001", 1000, "cmd-pump-ok")
        assert result["success"] is True
        assert result["data"]["status"] == "spray_started"
        assert result["data"]["duration_ms"] == 1000

    def test_missing_device_id_uses_default(self):
        """device_id is required at the API schema level; controller trusts the router."""
        ctrl = _fresh_controller()
        result = ctrl.manual_spray("", 1000, "cmd-empty-device")
        # Empty string device_id still reaches ESP32 — schema enforces non-empty
        assert result["success"] is True

    def test_missing_duration_ms_rejected(self):
        """duration_ms <= 0 must be rejected."""
        ctrl = _fresh_controller()
        result = ctrl.manual_spray("device-001", 0, "cmd-zero-dur")
        assert result["success"] is False
        assert result["error"]["code"] == "INVALID_DURATION"

    def test_missing_command_id_autogenerated(self):
        ctrl = _fresh_controller()
        result = ctrl.manual_spray("device-001", 1000)
        assert result["success"] is True
        assert result["data"]["command_id"].startswith("cmd-")

    def test_duration_zero_rejected(self):
        ctrl = _fresh_controller()
        result = ctrl.manual_spray("device-001", 0, "cmd-dur-zero")
        assert result["success"] is False
        assert result["error"]["code"] == "INVALID_DURATION"

    def test_duration_negative_rejected(self):
        ctrl = _fresh_controller()
        result = ctrl.manual_spray("device-001", -10, "cmd-dur-neg")
        assert result["success"] is False
        assert result["error"]["code"] == "INVALID_DURATION"

    def test_duration_exceeds_max_rejected(self):
        ctrl = _fresh_controller()
        result = ctrl.manual_spray("device-001", 5000, "cmd-dur-max")
        assert result["success"] is False
        assert result["error"]["code"] == "INVALID_DURATION"

    def test_duplicate_command_rejected(self):
        ctrl = _fresh_controller()
        result1 = ctrl.manual_spray("device-001", 1000, "cmd-dup-pump")
        assert result1["success"] is True

        ctrl._is_spraying = False
        result2 = ctrl.manual_spray("device-001", 1000, "cmd-dup-pump")
        assert result2["success"] is False
        assert result2["error"]["code"] == "DUPLICATE_COMMAND"

    def test_device_offline_handled(self, monkeypatch):
        ctrl = _fresh_controller()
        monkeypatch.setattr(serial_manager, "_connected", False)
        result = ctrl.manual_spray("device-001", 1000, "cmd-offline")
        assert result["success"] is False
        assert result["error"]["code"] == "DEVICE_OFFLINE"
        monkeypatch.setattr(serial_manager, "_connected", True)

    def test_emergency_stop_blocks_spraying(self):
        ctrl = _fresh_controller()
        ctrl._is_emergency_stopped = True
        result = ctrl.manual_spray("device-001", 1000, "cmd-estop-block")
        assert result["success"] is False
        assert result["error"]["code"] == "EMERGENCY_STOP_ACTIVE"

    def test_active_spray_blocks_conflicting_spray(self):
        ctrl = _fresh_controller()
        result1 = ctrl.manual_spray("device-001", 1000, "cmd-active-1")
        assert result1["success"] is True

        result2 = ctrl.manual_spray("device-001", 1000, "cmd-active-2")
        assert result2["success"] is False
        assert result2["error"]["code"] == "ALREADY_SPRAYING"


class TestStopBehavior:
    def test_stop_succeeds(self):
        ctrl = _fresh_controller()
        result = ctrl.stop("device-001")
        assert result["success"] is True
        assert result["data"]["status"] == "stopped"

    def test_stop_clears_spraying_flag(self):
        ctrl = _fresh_controller()
        ctrl._is_spraying = True
        ctrl.stop("device-001")
        assert ctrl.is_spraying is False


class TestEmergencyStop:
    def test_emergency_stop(self):
        ctrl = _fresh_controller()
        result = ctrl.emergency_stop()
        assert result["success"] is True
        assert ctrl.is_emergency_stopped is True

    def test_spray_blocked_after_estop(self):
        ctrl = _fresh_controller()
        ctrl.emergency_stop()
        result = ctrl.manual_spray("device-001", 1000)
        assert result["success"] is False
        assert result["error"]["code"] == "EMERGENCY_STOP_ACTIVE"

    def test_reset_emergency_stop(self):
        ctrl = _fresh_controller()
        ctrl.emergency_stop()
        ctrl.reset_emergency_stop()
        assert ctrl.is_emergency_stopped is False

    def test_reset_emergency_stop_requires_esp32_confirmation(self, monkeypatch):
        ctrl = _fresh_controller()
        ctrl.emergency_stop()
        monkeypatch.setattr(serial_manager, "send_command", lambda command: "ACK,ERROR,ESTOP_STILL_PRESSED")
        result = ctrl.reset_emergency_stop()
        assert result["success"] is False
        assert result["error"]["code"] == "ESTOP_STILL_PRESSED"
        assert ctrl.is_emergency_stopped is True

    def test_reset_emergency_stop_reports_communication_failure(self, monkeypatch):
        ctrl = _fresh_controller()
        ctrl.emergency_stop()
        monkeypatch.setattr(serial_manager, "send_command", lambda command: None)
        result = ctrl.reset_emergency_stop()
        assert result["success"] is False
        assert result["error"]["code"] == "COMMUNICATION_ERROR"
        assert ctrl.is_emergency_stopped is True


class TestModeControl:
    def test_set_valid_modes(self):
        ctrl = _fresh_controller()
        for mode in ["auto", "assisted", "manual"]:
            result = ctrl.set_mode(mode)
            assert result["success"] is True
            assert ctrl.current_mode == mode

    def test_set_invalid_mode(self):
        ctrl = _fresh_controller()
        result = ctrl.set_mode("turbo")
        assert result["success"] is False
        assert result["error"]["code"] == "INVALID_MODE"

    def test_wrong_mode_auto(self):
        ctrl = _fresh_controller()
        ctrl._current_mode = "auto"
        result = ctrl.manual_spray("device-001", 1000, "cmd-mode-auto")
        assert result["success"] is False
        assert result["error"]["code"] == "WRONG_MODE"

    def test_wrong_mode_assisted(self):
        ctrl = _fresh_controller()
        ctrl._current_mode = "assisted"
        result = ctrl.manual_spray("device-001", 1000, "cmd-mode-assisted")
        assert result["success"] is False
        assert result["error"]["code"] == "WRONG_MODE"


class TestStatus:
    def test_status_online(self):
        ctrl = _fresh_controller()
        result = ctrl.get_status("device-001")
        assert result["success"] is True
        assert result["data"]["status"] == "online"

    def test_status_returns_mode(self):
        ctrl = _fresh_controller()
        ctrl._current_mode = "assisted"
        result = ctrl.get_status("device-001")
        assert result["data"]["mode"] == "assisted"

    def test_status_no_servo_field(self):
        """Status response must not contain servo_angle."""
        ctrl = _fresh_controller()
        result = ctrl.get_status("device-001")
        assert "servo_angle" not in result["data"]
